spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/training_db
    username: postgres
    #password:
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      idle-timeout: 600000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
    show-sql: true
    format_sql: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    date-format: json.dateformat.custom
    locale: fr_FR
  profiles:
    active: production
  thymeleaf:
    cache: false

server:
  port: 8080

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG

# Flyway / Liquibase options (si utilisées)
# spring.flyway.enabled: true
# spring.flyway.locations: classpath:db/migration
