spring:
  springdoc:
    api-docs:
      path: /v3/api-docs          # Point d’accès aux docs OpenAPI (par défaut : /v3/api-docs)
    swagger-ui:
      path: /swagger-ui     # URL de l’UI (par défaut : /swagger-ui.html)
      operationsSorter: method
      tagsSorter: alpha
      display-request-duration: true
      doc-expansion: none
    show-actuator: false      # Facultatif : désactiver la doc des endpoints actuator

  datasource:
    url:  ${DB_URL} # Remplacez le port et le nom de la base de données selon vos besoins
    username: ${DB_USERNAME}  # Remplacez par votre nom d'utilisateur MySQL
    password: ${DB_PASSWORD}  # Définissez votre mot de passe MySQL
    driver-class-name: ${DB_DRIVER}  # Le driver MySQL
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      idle-timeout: 600000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: ${DB_DIALECT} # Dialecte MySQL (version 8)
        jdbc:
          time_zone: UTC
    show-sql: true
    format_sql: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    date-format: "dd/MM/yyyy"  # Format de date : jour/mois/année
    locale: fr_FR
  profiles:
    active: production
  thymeleaf:
    cache: false

server:
  port: ${SERVER_PORT}

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION}      # 15 minutes
  refresh-expiration-ms: ${JWT_EXPIRATION_REFRESH}  # 7 days



# Flyway / Liquibase options (si utilisés)
# spring.flyway.enabled: true
# spring.flyway.locations: classpath:db/migration
